spring:
  application:
    name: PAYMENT-SERVICE

#Stripe payment gateway
stripe:
  api:
    publicKey: ${pk}
    secretKey: ${sk}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true